import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import './globals.css';
import Footer from "@/components/employee_Footer"; 
import RootLayoutWrapper from "@/components/RootLayoutWrapper";
import NavBar from "@/components/NavBar";
import DbConnectionStatus from "@/components/DbConnectionStatus";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <body className={GeistSans.className}>
        <main className="flex-grow">
          <RootLayoutWrapper>
            {children}
          </RootLayoutWrapper>
        </main>
        <Footer />
        <DbConnectionStatus />
      </body>
    </html>
  );
}
